# Data wrangling
The goal of the functions presented in this document is to manipulate data obtained in previous steps

In [4]:
import pandas as pd

In [5]:
organismos = pd.read_csv("organismos.txt", sep=",")
k01220 = pd.read_csv("K01220.txt", sep=",")

Function `merge_dfs()` aims to combine data from both dataframes $\textbf{K01220}$ and $\textbf{organismos}$. For each element of the column $\textit{'Organisms'}$ in $\textbf{K01220}$ it searches into $\textit{'code'}$ column elements from $\textbf{organismos}$ to look for any coincidences. If both elements match, then the row of the element on $\textbf{organismos}$ should be saved. At the end of the entire function you should have those saved rows appended next to $\textbf{K01220}$

This was my first attempt to create the `merge_dfs()` function, it turns out that it works, but works on a time complexity $\textit{O(n · m)}$. Which results convenient when working with small data. If this was about just working with Python vanilla would be correct.

In [7]:
# def merge_dfs(k01220, organismos):
#     lista = []
#     for i in range(len(k01220)):
#         for j in range(len(organismos)):
#             if k01220["Organims"].loc[i] == organismos["code"].loc[j]:
#                 lista.append(organismos.loc[j])
#                 break 
#     return pd.DataFrame(lista)
# lista_orgs = merge_dfs(k01220, organismos)
# 
# lista_orgs = lista_orgs.drop(["entry", "code"], axis=1)  ##remove duplicate columns 
# k01220_phylo = pd.concat([k01220, lista_orgs], axis=1)   ## column-bind k01220 and resulting list  
# k01220_phylo.to_csv('k01220_phylo.txt', sep=",", index=False)

But since I'am using $\text{Pandas}$ Python library, there is a method called $\text{pd.merge(df, df2, params...)}$ that does exactly the same than my previous function but with a radical change on time complexity, being this time $\textit{O(n + m)}$. 

The new `merge_dfs()` function implements this method an expects two dataframes and the name of two columns of those dataframes. This function takes the shared elements and their respective rows ant applies some sort of $\text{"rbind"}$ from R. And outputs a dataframe with merged dfs.

In [9]:
def merge_dfs(k01220, organismos, left_col, right_col):
    return pd.merge(k01220, organismos, left_on=left_col, right_on=right_col, how='inner')

lista_orgs = merge_dfs(k01220, organismos, "Organims", "code")      # merge both dfs
lista_orgs = lista_orgs.drop(["entry", "code"], axis=1)             # delete a couple columns with useless info

In [49]:
lista_orgs.head(3)

,Organims,id_Entry,Genes,amino_Length,amino_Sequence,nucl_Length,nucl_Sequence,organism,phylogeny
0,sdo,SD1155_00675,lacG,470,MTKKLPEDFIFGGATAAYQAEGATQTDGKGRVAWDTYLEENYWYTA...,1413,atgactaaaaaattacctgaagattttatttttggtggagcgactg...,Sulfitobacter donghicola,Prokaryotes;Bacteria;Alphaproteobacteria;Sulfi...
1,enem,PVA44_07260,lacG,477,MTKYTFPENFFFGAATAAYQAEGATDIGGKGKVAWDEMYHRESSTF...,1434,atgactaaatatacctttccagagaattttttctttggagcagcaa...,Entomospira nematocerorum,Prokaryotes;Bacteria;Spirochaetota;Entomospira
2,eet,PVA45_07505,lacG,477,MPKYTFTDNFFFGAATAAYQAEGATDVGGKGKVAWDEMYHRANSTF...,1434,atgcctaaatatacctttacagataacttcttttttggagcagcca...,Entomospira entomophila,Prokaryotes;Bacteria;Spirochaetota;Entomospira

In [41]:
lista_orgs.to_csv('k01220_phylo.txt', sep=",", index=False)

In [93]:
k01220_phylo = pd.read_csv("k01220_phylo.txt", sep=',')
k01220_phylo.head(3)

,Organims,id_Entry,Genes,amino_Length,amino_Sequence,nucl_Length,nucl_Sequence,organism,phylogeny
0,sdo,SD1155_00675,lacG,470,MTKKLPEDFIFGGATAAYQAEGATQTDGKGRVAWDTYLEENYWYTA...,1413,atgactaaaaaattacctgaagattttatttttggtggagcgactg...,Sulfitobacter donghicola,Prokaryotes;Bacteria;Alphaproteobacteria;Sulfi...
1,enem,PVA44_07260,lacG,477,MTKYTFPENFFFGAATAAYQAEGATDIGGKGKVAWDEMYHRESSTF...,1434,atgactaaatatacctttccagagaattttttctttggagcagcaa...,Entomospira nematocerorum,Prokaryotes;Bacteria;Spirochaetota;Entomospira
2,eet,PVA45_07505,lacG,477,MPKYTFTDNFFFGAATAAYQAEGATDVGGKGKVAWDEMYHRANSTF...,1434,atgcctaaatatacctttacagataacttcttttttggagcagcca...,Entomospira entomophila,Prokaryotes;Bacteria;Spirochaetota;Entomospira

Until this moment we created a dataframe which is made from shared information from two other dataframes and save it to a text file. Now the next step is to take the desired information from this new dataframe and create a fasta file.

The next function `clean_df()` takes the resulting dataframe from `merge_dfs()`, the idea of this function is to return a dataframe with the fields  ready to bee transformed to a fasta file. We begin creating a variable `headers` that is made from joining the content of one or more columns (two columns in this case) to create just one column withe the content of the previous. This new variable is concatenated to another that should contain the sequences.  

The function `to_fasta()` uses the resulting dataframe from `clean_df()` and also requires a string that will serve as separator from the header and the sequence, typically fasta format uses a `'\n'` to achive this. The idea of `clean_df()` is to prepare data then give format with `to_fasta()` and later save as fasta.

In [60]:
def clean_df(lista_orgs, headers, seqs):
    headers = lista_orgs[headers].fillna('').agg(' '.join, axis=1)                            #joins content of desired columns and
    return pd.concat([headers, lista_orgs[seqs]], axis=1).rename(columns={0:'headers'})       #joins columns and rename a column

def to_fasta(headers_seqs, separator, seqs):
    if type(separator)==str:
        headers_seqs['headers'] = '>' + headers_seqs['headers']                               #append '>' before each element in column 'headers'
        headers_seqs[seqs] = headers_seqs[seqs] + '\n'                                        #adds a line break at the end of the sequence
        headers_export = headers_seqs.agg(separator.join, axis=1)                             #applies "".join a las filas   
        return separator.join(headers_export)                                                 #convierte la Series final a string con separator entre 
                                                                                              #registros

In [31]:
headers = ['Organims', 'id_Entry']
seqs = 'amino_Sequence'

headers_seqs = clean_df(lista_orgs, headers, seqs)
final_fasta = to_fasta(headers_seqs, '\n', seqs)

In [ ]:
with open('k01220.fas', 'w') as f:   #write fasta, might throw an error Errno 22, restart the entire kernel or close everything and restart
    f.write(final_fasta)

Now We need to make a sligth variation of the parameters when creating the header of the fasta file. For commodity pourposes We will modify the header content so it will be made of the scientific name and the gene (if it exist).

In [65]:
lista_orgs.head(1)

,Organims,id_Entry,Genes,amino_Length,amino_Sequence,nucl_Length,nucl_Sequence,organism,phylogeny
0,sdo,SD1155_00675,lacG,470,MTKKLPEDFIFGGATAAYQAEGATQTDGKGRVAWDTYLEENYWYTA...,1413,atgactaaaaaattacctgaagattttatttttggtggagcgactg...,Sulfitobacter donghicola,Prokaryotes;Bacteria;Alphaproteobacteria;Sulfi...

In [69]:
nuevo_headers = ['organism', 'Genes']
aa_seqs = 'amino_Sequence'
nt_seqs = 'nucl_Sequence'
n_headers_aa = clean_df(lista_orgs, nuevo_headers, aa_seqs)
n_headers_nt = clean_df(lista_orgs, nuevo_headers, nt_seqs)

In [77]:
n_headers_aa.head(2)

,headers,amino_Sequence
0,Sulfitobacter donghicola lacG,MTKKLPEDFIFGGATAAYQAEGATQTDGKGRVAWDTYLEENYWYTA...
1,Entomospira nematocerorum lacG,MTKYTFPENFFFGAATAAYQAEGATDIGGKGKVAWDEMYHRESSTF...

In [79]:
n_headers_nt.head(2)

,headers,nucl_Sequence
0,Sulfitobacter donghicola lacG,atgactaaaaaattacctgaagattttatttttggtggagcgactg...
1,Entomospira nematocerorum lacG,atgactaaatatacctttccagagaattttttctttggagcagcaa...

In [87]:
aa_fasta = to_fasta(n_headers_aa, '\n', aa_seqs)
nt_fasta = to_fasta(n_headers_nt, '\n', nt_seqs)

In [89]:
with open('k01220_aa_names.fas', 'w') as f:   #write fasta, might throw an error Errno 22, restart the entire kernel or close everything and restart
    f.write(aa_fasta)

In [91]:
with open('k01220_nt_names.fas', 'w') as f:   #write fasta, might throw an error Errno 22, restart the entire kernel or close everything and restart
    f.write(nt_fasta)